; PlatformIO Project Configuration File for Seeed Studio XIAO ESP32C6
; Quadruped 12-Servo Calibration with PCA9685, SSD1306 OLED & Buzzer

[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.2
    adafruit/Adafruit SSD1306@^2.5.13
    adafruit/Adafruit GFX Library@^1.11.11
    Wire
    SPI
